name: MCP CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    name: Lint check
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 20

      - name: Install dependencies & build
        run: npm install

      - name: Run check
        run: npm run lint:check

  publish-dry-run:
    needs: [ check ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: 🚀Publish
        run: npm publish --dry-run
